import Head from "next/head";

const Layout = ({ title, desc, children }) => {
  return (
    <div className="bg-white-200 min-h-screen">
      <Head>
        <title>{title ? title : "Create Next App"}</title>
        <meta
          name="description"
          content={desc ? desc : "Generated by create next app"}
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="px-20 py-16">{children}</div>
    </div>
  );
};

export default Layout;
